name: Update Holiday

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.5'

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install dependencies
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_seconds: 60
          max_attempts: 3
          command: composer install --quiet --no-plugins --no-ansi --prefer-dist --no-progress --no-interaction

      - name: Update
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_seconds: 60
          max_attempts: 3
          command: php bin/holiday-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: Update Holiday
          delete-branch: true
          title: Update Holiday
          body: |
            Holiday have been updated.
